[5.09.30] Bricked Blast Furnace
Blood-Asp/GT5-Unofficial pull request #1099
Opened 2017-06-17 22:36 UTC by JohannesGaessler

As a way of rebalancing the Bronze Age I have added a Blast Furnace that is built from bricks.
This eliminates the need to gather large amounts of Bronze for a Bronze Blast Furnace.

![2017-06-08_22 51 52](https://user-images.githubusercontent.com/18492268/27256664-47afcbe8-53bd-11e7-9c59-e78d9defc0c0.png)

The Bricked Blast Furnace has the same structure as the Bronze Blast Furnace and is built from Firebricks.
Firebricks are made from clay, but they require more complex processing.

To build a Bricked Blast Furnace the player needs to build a Steam Compressor and a Steam Hammer/Steam Macerator.
The first Bricked Blast Furnace requires a total of 130 Clay blocks to build.
This is comparable to the 150 Bronze required for a Bronze Blast Furnace, but clay is found much more common than Copper and Tin, therefore reducing the amount of time the player needs to spend on searching for a vein.

On another note, NEI recipes for the primitive blast furnaces have been added.

2017-06-21 11:46 UTC, Rongmario commented
There is a complete GT version up for compile with this and the OilRefinery update on my fork of GT5U.

2017-06-22 22:53 UTC, draknyte1 commented on src/main/java/gregtech/common/GT_RecipeAdder.java
> +        	GT_Recipe.GT_Recipe_Map.sPrimitiveBlastRecipes.addRecipe(true, new ItemStack[]{aInput1, aInput2, coalStack}, new ItemStack[]{aOutput1, aOutput2, Materials.Ash.getDustTiny(aCoalAmount)}, null
Normal Coal and Coke produce different types of ash..

2017-06-22 22:54 UTC, draknyte1 commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_PrimitiveBlastFurnace.java
> +		return new GT_MetaTileEntity_BronzeBlastFurnace(this.mName);
Is this intended?

2017-06-22 23:04 UTC, Techlone commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_PrimitiveBlastFurnace.java
> +		return new GT_MetaTileEntity_BronzeBlastFurnace(this.mName);
The copy-paste mistake
Happens

2017-06-22 23:05 UTC, draknyte1 requested changes
So, 95% of it looks good.
Just be sure to change the things noted and add a config and I see no issues otherwise.

Also be sure the BBF uses the BBF GUI and TE, whilst the bricked one uses the Bricked GUI and TE.
Don't remember which the BBF uses, the diffing is ugh online due to everything having moved a line.

2017-06-22 23:06 UTC, draknyte1 commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_PrimitiveBlastFurnace.java
> +		return new GT_MetaTileEntity_BronzeBlastFurnace(this.mName);
Just pointing things out during my review.

2017-06-23 23:25 UTC, Techlone commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_BrickedBlastFurnace.java
> +                "Built from 32 Firerick blocks",
*fire**b**rick

2017-06-25 21:46 UTC, merged