Add new zpm and MAX voltage battery and change ultimate battery
Blood-Asp/GT5-Unofficial pull request #1147
Opened 2017-07-08 14:49 UTC by SLiMylya

add new battery
![2017-07-08_17 35 03](https://user-images.githubusercontent.com/10255529/27986254-7e07c58a-6405-11e7-98a4-57d7d8cad8d4.png)
![2017-07-08_17 36 19](https://user-images.githubusercontent.com/10255529/27986256-860cb0ce-6405-11e7-9b50-20baa1562697.png)
change
![2017-07-08_17 35 49](https://user-images.githubusercontent.com/10255529/27986257-909590d8-6405-11e7-9faf-7ea118941007.png)

2017-07-08 17:11 UTC, draknyte1 commented
We're not changing the storage of the ultimate battery.

2017-07-08 18:07 UTC, Techlone commented
@draknyte1 what's a problem with it?

2017-07-08 18:17 UTC, Blood-Asp commented
Personally i would prefer to keep MAX Voltage only as transfer Voltage, not for storage.

2017-07-08 18:25 UTC, SapientMC commented
@Blood-Asp we can change MAX voltage to 2M eU/t

2017-07-08 18:28 UTC, Blood-Asp commented
I mean the highest Power tier should be Transfer only. Same as EV for IC2 alone.

2017-07-08 18:57 UTC, SapientMC commented
@Blood-Asp why? This will simply require a transformer at both ends of the line.

2017-07-08 19:22 UTC, draknyte1 commented
It should stay as a max value. 
Why change it? I disapprove of this PR until the original values for max are restored.

2017-07-08 19:22 UTC, draknyte1 requested changes
Restore Max voltage battery capacity.

2017-07-08 19:54 UTC, Antillar commented
What about adding the most expensive battery craft (currently requested Max) to be UV, but already charged? It would set new goals for players in the endgame. 
The recipe can be made more expensive then.

2017-07-09 07:15 UTC, SLiMylya commented
change
![2017-07-09_10 10 35](https://user-images.githubusercontent.com/10255529/27991948-808107b0-648f-11e7-8784-29cf8ee06f79.png)
or delete her?

2017-07-09 07:20 UTC, draknyte1 commented
Leave the old battery as is..

If you want a zpm battery, add a config option to make empty ZPM's craftable and rechargeable.

2017-07-09 07:27 UTC, SLiMylya commented
old battery on max storage not  automated

2017-07-09 07:52 UTC, draknyte1 commented
I don't understand sorry. 
MAX violate will, as blood suggests, be for power transfer and not storage.

2017-07-09 08:42 UTC, SLiMylya commented
Sorry, max capacity

2017-07-09 09:18 UTC, Dragon2488 requested changes

2017-07-09 09:18 UTC, Dragon2488 commented on src/main/java/gregtech/common/items/GT_MetaGenerated_Item_01.java
> -        setElectricStats(32000 + tLastID, Long.MAX_VALUE, GT_Values.V[8], 8L, -3L, true);
Do not touch Ultimate Battery max charge. Or make this change it optional.

2017-07-09 09:26 UTC, draknyte1 commented on src/main/java/gregtech/common/items/GT_MetaGenerated_Item_01.java
> -        setElectricStats(32000 + tLastID, Long.MAX_VALUE, GT_Values.V[8], 8L, -3L, true);
Easier to just not change it and make a UV tier battery that holds less. 

Then make a config option to make  zpm craftable and rechargeable

2017-07-09 09:44 UTC, SLiMylya commented
Create zpm, create UV capacity 100,000,000,000.and do not touch ultimate battery. I understand correctly?

2017-07-09 10:00 UTC, draknyte1 commented
ZPM battery exists, it is single use. 
Just make config option to add recipe and allow it to be rechargeable.

2017-07-09 16:45 UTC, SLiMylya commented
update pr

2017-07-17 09:59 UTC, SLiMylya commented
add config EnableZPMandUVBatteries default false

2017-08-11 12:52 UTC, Blood-Asp commented
From what i can see are the requested changes done. So re-rewiew?

2017-09-03 12:39 UTC, merged