Compressed Block registry rework
Blood-Asp/GT5-Unofficial pull request #1290
Opened 2017-11-19 12:02 UTC by Antifluxfield

Why you are registering those compressed blocks with the algorithm highly depending on the order of the materials?

2017-11-19 13:42 UTC, Exidex requested changes
Fix your whitespaces and formatting, also there is RegistryNamespaced#getIDForObject method that does exactly the same as the one you added

2017-11-19 15:44 UTC, Antifluxfield commented
Done.

2017-11-20 17:33 UTC, Exidex reviewed
So, going to the point. I am not sure if this change is necessary. Existing code and proposed, both have a requirement not to change material ids order. The only difference I see is if we'll want to make material 'not ignored' (I don't think will want to do that) or change a material type, this will not break backward compatibility, but this is at the cost of increasing amount of blocks created. Also this code will change in 1.13 because of vanilla changes.

2017-11-21 05:37 UTC, Antifluxfield commented
You should know that the order of the materials are always more volatile than the fixed ids. Imagine someone register his own material through the configs or by an addon:
Suppose our current materials is occupying the id segment O, an addon registered its materials to id segment A, and we append some materials once in an update in id segment B. Assume that A is following B, If a player takes the addon before taking the update, the order of the materials will change form "O->A" to "O->B->A", and breaking the backward compatibility. Same thing will happen if A lays before B and the player takes the addon after the update.
The only way to solve this issue is to patch a config to adjust the ids for each case when you want to append some material, and let the players/modpackers to set them to a proper value - I don't think that's a good idea since we can fix it know.

2017-11-23 06:34 UTC, Exidex requested changes

2017-11-23 06:34 UTC, Exidex commented on src/main/java/gregtech/common/blocks/MetaBlocks.java
> +            	int id = Material.MATERIAL_REGISTRY.getIDForObject(material), index = id / 16;
I spend some time looking where index was declared. Separate this line into two and we are good to merge

2017-11-25 18:36 UTC, merged